// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1749821399);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1749821395);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{d740d805-4c30-4615-a306-839f6e4e0480}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1749821378);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"8337910764091155\":1749821389917,\"2430995858574347\":1749821389929,\"8963056281975588\":1749821389933,\"8886666166501165\":1749821392294,\"4696859089181202\":1749821392320,\"7183465859430821\":1749821392365,\"6861456205727054\":1749821392393,\"1981542663886948\":1749821392410,\"5570076867371628\":1749821392459,\"1554296534307570\":1749821394499,\"4221717352818780\":1749821394505,\"2113456827592458\":1749821394542,\"6266613851305673\":1749821394633,\"412903719520045\":1749821394663,\"2436864239949816\":1749821394720,\"114282763128414\":1749821394743,\"2383921302366047\":1749821394754,\"5392953700411972\":1749821394766}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{60a03caf-5b3a-438b-9b46-75adbde02277}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1749821381);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1749821395995");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1749842995995");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1749821396");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230522134052");
user_pref("browser.startup.homepage_override.mstone", "113.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1749821382);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1749821389423");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "113.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "3cbb1e92cba941a7b598bed5b8b30ad7");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1749821380);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230522134052");
user_pref("extensions.lastAppVersion", "113.0.2");
user_pref("extensions.lastPlatformVersion", "113.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"0c7b5232-017d-4f00-92f4-5f106ea9cbfc\",\"pictureinpicture@mozilla.org\":\"2f240303-de21-4dad-a4f9-8d63e4f3e085\",\"screenshots@mozilla.org\":\"39d36d08-4752-474f-8cf3-659c5ab67c31\",\"webcompat-reporter@mozilla.org\":\"57ce8c5f-e821-48db-9010-5aa9c30405eb\",\"webcompat@mozilla.org\":\"98b85975-d449-4ad2-8f0e-5f42e95abb95\",\"default-theme@mozilla.org\":\"155b8daa-48ec-4ae3-9bc4-6ec012a764ce\",\"addons-search-detection@mozilla.com\":\"a19f28ac-8143-4444-85bc-69d30fe505a6\",\"google@search.mozilla.org\":\"016bbaaa-de13-4838-8ab4-7ce529656eff\",\"wikipedia@search.mozilla.org\":\"eb401b7a-c966-408f-841a-88c0aba40d9c\",\"bing@search.mozilla.org\":\"573adda1-a4fc-4bc4-af29-c57677b47ae8\",\"ddg@search.mozilla.org\":\"9b8518f4-c223-4eb1-8119-991483cbdbdd\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "388f05b3-1c5b-4d61-9f2c-5abfac8504cd");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.telemetry.cachedClientID", "0d968b33-57d5-41ed-8728-873bd53ccf0f");
user_pref("toolkit.telemetry.previousBuildID", "20230522134052");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
